In [1]:
import numpy as np

In [2]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])

In [5]:
epochs = 10000
lr = 0.1
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

In [6]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

In [7]:
print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.25169707 0.20018949] [0.09410244 0.98548048]
Initial hidden biases: [0.44678569 0.17777885]
Initial output weights: [0.47457166] [0.14203807]
Initial output biases: [0.40778596]


In [8]:
#Training algorithm

In [9]:
for _ in range(epochs):
    #Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)

    #Backpropagation
    error = expected_output - predicted_output
    print(error)    
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr

[[-0.68450012]
 [ 0.30662477]
 [ 0.30810102]
 [-0.70005971]]
[[-0.6782014 ]
 [ 0.31340455]
 [ 0.31458357]
 [-0.69314262]]
[[-0.67198988]
 [ 0.32009935]
 [ 0.32098081]
 [-0.68630746]]
[[-0.66587684]
 [ 0.32669615]
 [ 0.32728076]
 [-0.67956793]]
[[-0.65987261]
 [ 0.33318291]
 [ 0.33347239]
 [-0.67293672]]
[[-0.65398651]
 [ 0.3395487 ]
 [ 0.33954572]
 [-0.66642538]]
[[-0.64822681]
 [ 0.34578376]
 [ 0.34549184]
 [-0.66004428]]
[[-0.64260073]
 [ 0.35187949]
 [ 0.35130294]
 [-0.65380259]]
[[-0.63711441]
 [ 0.35782851]
 [ 0.35697234]
 [-0.64770823]]
[[-0.63177295]
 [ 0.3636246 ]
 [ 0.36249446]
 [-0.6417679 ]]
[[-0.62658042]
 [ 0.3692627 ]
 [ 0.36786477]
 [-0.63598711]]
[[-0.62153992]
 [ 0.37473886]
 [ 0.3730798 ]
 [-0.6303702 ]]
[[-0.61665363]
 [ 0.3800502 ]
 [ 0.37813703]
 [-0.62492043]]
[[-0.61192286]
 [ 0.38519478]
 [ 0.38303485]
 [-0.61964002]]
[[-0.60734813]
 [ 0.39017163]
 [ 0.3877725 ]
 [-0.61453023]]
[[-0.60292924]
 [ 0.39498057]
 [ 0.39234999]
 [-0.60959145]]
[[-0.59866532]
 [ 0.3996

[[-0.50107387]
 [ 0.50184081]
 [ 0.49703839]
 [-0.50016458]]
[[-0.50107013]
 [ 0.50183868]
 [ 0.49704102]
 [-0.50016744]]
[[-0.50106639]
 [ 0.50183655]
 [ 0.49704365]
 [-0.50017029]]
[[-0.50106265]
 [ 0.50183442]
 [ 0.49704627]
 [-0.50017314]]
[[-0.50105891]
 [ 0.50183229]
 [ 0.4970489 ]
 [-0.50017599]]
[[-0.50105518]
 [ 0.50183016]
 [ 0.49705152]
 [-0.50017884]]
[[-0.50105145]
 [ 0.50182803]
 [ 0.49705414]
 [-0.50018168]]
[[-0.50104773]
 [ 0.50182591]
 [ 0.49705676]
 [-0.50018452]]
[[-0.50104401]
 [ 0.50182378]
 [ 0.49705938]
 [-0.50018737]]
[[-0.50104029]
 [ 0.50182166]
 [ 0.497062  ]
 [-0.50019021]]
[[-0.50103657]
 [ 0.50181953]
 [ 0.49706461]
 [-0.50019304]]
[[-0.50103286]
 [ 0.50181741]
 [ 0.49706722]
 [-0.50019588]]
[[-0.50102915]
 [ 0.50181529]
 [ 0.49706983]
 [-0.50019872]]
[[-0.50102545]
 [ 0.50181317]
 [ 0.49707244]
 [-0.50020155]]
[[-0.50102174]
 [ 0.50181105]
 [ 0.49707505]
 [-0.50020438]]
[[-0.50101804]
 [ 0.50180893]
 [ 0.49707766]
 [-0.50020721]]
[[-0.50101435]
 [ 0.5018

[[-0.49953038]
 [ 0.50088605]
 [ 0.49816068]
 [-0.50140003]]
[[-0.49952772]
 [ 0.50088429]
 [ 0.49816265]
 [-0.50140227]]
[[-0.49952507]
 [ 0.50088252]
 [ 0.49816461]
 [-0.50140451]]
[[-0.49952242]
 [ 0.50088075]
 [ 0.49816658]
 [-0.50140676]]
[[-0.49951977]
 [ 0.50087898]
 [ 0.49816855]
 [-0.501409  ]]
[[-0.49951712]
 [ 0.50087721]
 [ 0.49817051]
 [-0.50141123]]
[[-0.49951447]
 [ 0.50087545]
 [ 0.49817247]
 [-0.50141347]]
[[-0.49951183]
 [ 0.50087368]
 [ 0.49817444]
 [-0.50141571]]
[[-0.49950918]
 [ 0.50087192]
 [ 0.4981764 ]
 [-0.50141795]]
[[-0.49950654]
 [ 0.50087015]
 [ 0.49817836]
 [-0.50142018]]
[[-0.4995039 ]
 [ 0.50086839]
 [ 0.49818032]
 [-0.50142242]]
[[-0.49950126]
 [ 0.50086663]
 [ 0.49818228]
 [-0.50142466]]
[[-0.49949862]
 [ 0.50086486]
 [ 0.49818423]
 [-0.50142689]]
[[-0.49949598]
 [ 0.5008631 ]
 [ 0.49818619]
 [-0.50142912]]
[[-0.49949335]
 [ 0.50086134]
 [ 0.49818815]
 [-0.50143136]]
[[-0.49949071]
 [ 0.50085958]
 [ 0.4981901 ]
 [-0.50143359]]
[[-0.49948808]
 [ 0.5008

[[-0.49852564]
 [ 0.50019   ]
 [ 0.49889879]
 [-0.50228548]]
[[-0.49852341]
 [ 0.5001884 ]
 [ 0.49890039]
 [-0.50228753]]
[[-0.49852118]
 [ 0.5001868 ]
 [ 0.498902  ]
 [-0.50228958]]
[[-0.49851895]
 [ 0.50018521]
 [ 0.4989036 ]
 [-0.50229164]]
[[-0.49851672]
 [ 0.50018361]
 [ 0.4989052 ]
 [-0.50229369]]
[[-0.49851449]
 [ 0.50018201]
 [ 0.4989068 ]
 [-0.50229575]]
[[-0.49851226]
 [ 0.50018042]
 [ 0.4989084 ]
 [-0.5022978 ]]
[[-0.49851003]
 [ 0.50017882]
 [ 0.49891   ]
 [-0.50229986]]
[[-0.49850781]
 [ 0.50017722]
 [ 0.4989116 ]
 [-0.50230191]]
[[-0.49850558]
 [ 0.50017563]
 [ 0.4989132 ]
 [-0.50230396]]
[[-0.49850335]
 [ 0.50017403]
 [ 0.4989148 ]
 [-0.50230602]]
[[-0.49850113]
 [ 0.50017244]
 [ 0.4989164 ]
 [-0.50230807]]
[[-0.4984989 ]
 [ 0.50017084]
 [ 0.49891799]
 [-0.50231012]]
[[-0.49849668]
 [ 0.50016925]
 [ 0.49891959]
 [-0.50231218]]
[[-0.49849445]
 [ 0.50016765]
 [ 0.49892118]
 [-0.50231423]]
[[-0.49849223]
 [ 0.50016606]
 [ 0.49892278]
 [-0.50231628]]
[[-0.49849001]
 [ 0.5001

[[-0.49767537]
 [ 0.49957071]
 [ 0.49948683]
 [-0.50309865]]
[[-0.49767327]
 [ 0.49956916]
 [ 0.49948822]
 [-0.50310073]]
[[-0.49767117]
 [ 0.49956762]
 [ 0.4994896 ]
 [-0.50310281]]
[[-0.49766907]
 [ 0.49956607]
 [ 0.49949098]
 [-0.5031049 ]]
[[-0.49766697]
 [ 0.49956452]
 [ 0.49949236]
 [-0.50310698]]
[[-0.49766487]
 [ 0.49956297]
 [ 0.49949375]
 [-0.50310907]]
[[-0.49766277]
 [ 0.49956142]
 [ 0.49949513]
 [-0.50311115]]
[[-0.49766067]
 [ 0.49955987]
 [ 0.49949651]
 [-0.50311324]]
[[-0.49765857]
 [ 0.49955833]
 [ 0.49949789]
 [-0.50311532]]
[[-0.49765647]
 [ 0.49955678]
 [ 0.49949927]
 [-0.50311741]]
[[-0.49765437]
 [ 0.49955523]
 [ 0.49950065]
 [-0.50311949]]
[[-0.49765228]
 [ 0.49955368]
 [ 0.49950202]
 [-0.50312158]]
[[-0.49765018]
 [ 0.49955213]
 [ 0.4995034 ]
 [-0.50312367]]
[[-0.49764808]
 [ 0.49955058]
 [ 0.49950478]
 [-0.50312575]]
[[-0.49764598]
 [ 0.49954903]
 [ 0.49950616]
 [-0.50312784]]
[[-0.49764388]
 [ 0.49954749]
 [ 0.49950753]
 [-0.50312993]]
[[-0.49764178]
 [ 0.4995

[[-0.49641681]
 [ 0.49864232]
 [ 0.50023776]
 [-0.50440489]]
[[-0.49641451]
 [ 0.49864064]
 [ 0.50023898]
 [-0.50440736]]
[[-0.49641222]
 [ 0.49863897]
 [ 0.5002402 ]
 [-0.50440983]]
[[-0.49640992]
 [ 0.49863729]
 [ 0.50024142]
 [-0.50441231]]
[[-0.49640763]
 [ 0.49863561]
 [ 0.50024264]
 [-0.50441478]]
[[-0.49640533]
 [ 0.49863393]
 [ 0.50024385]
 [-0.50441726]]
[[-0.49640303]
 [ 0.49863225]
 [ 0.50024507]
 [-0.50441973]]
[[-0.49640073]
 [ 0.49863057]
 [ 0.50024629]
 [-0.50442221]]
[[-0.49639843]
 [ 0.49862889]
 [ 0.50024751]
 [-0.50442469]]
[[-0.49639613]
 [ 0.4986272 ]
 [ 0.50024872]
 [-0.50442717]]
[[-0.49639383]
 [ 0.49862552]
 [ 0.50024994]
 [-0.50442965]]
[[-0.49639153]
 [ 0.49862384]
 [ 0.50025116]
 [-0.50443213]]
[[-0.49638923]
 [ 0.49862216]
 [ 0.50025238]
 [-0.50443461]]
[[-0.49638693]
 [ 0.49862047]
 [ 0.50025359]
 [-0.5044371 ]]
[[-0.49638462]
 [ 0.49861879]
 [ 0.50025481]
 [-0.50443958]]
[[-0.49638232]
 [ 0.49861711]
 [ 0.50025603]
 [-0.50444207]]
[[-0.49638001]
 [ 0.4986

[[-0.49562109]
 [ 0.49806738]
 [ 0.50062782]
 [-0.50527556]]
[[-0.49561847]
 [ 0.49806552]
 [ 0.500629  ]
 [-0.50527846]]
[[-0.49561585]
 [ 0.49806365]
 [ 0.50063017]
 [-0.50528137]]
[[-0.49561323]
 [ 0.49806179]
 [ 0.50063135]
 [-0.50528427]]
[[-0.49561061]
 [ 0.49805992]
 [ 0.50063253]
 [-0.50528718]]
[[-0.49560798]
 [ 0.49805805]
 [ 0.5006337 ]
 [-0.50529009]]
[[-0.49560536]
 [ 0.49805618]
 [ 0.50063488]
 [-0.505293  ]]
[[-0.49560273]
 [ 0.49805431]
 [ 0.50063606]
 [-0.50529591]]
[[-0.4956001 ]
 [ 0.49805245]
 [ 0.50063723]
 [-0.50529883]]
[[-0.49559748]
 [ 0.49805057]
 [ 0.50063841]
 [-0.50530174]]
[[-0.49559485]
 [ 0.4980487 ]
 [ 0.50063959]
 [-0.50530466]]
[[-0.49559222]
 [ 0.49804683]
 [ 0.50064076]
 [-0.50530758]]
[[-0.49558958]
 [ 0.49804496]
 [ 0.50064194]
 [-0.5053105 ]]
[[-0.49558695]
 [ 0.49804309]
 [ 0.50064311]
 [-0.50531342]]
[[-0.49558432]
 [ 0.49804121]
 [ 0.50064429]
 [-0.50531634]]
[[-0.49558168]
 [ 0.49803934]
 [ 0.50064547]
 [-0.50531927]]
[[-0.49557904]
 [ 0.4980

[[-0.49451192]
 [ 0.4972964 ]
 [ 0.50106778]
 [-0.50651898]]
[[-0.49450866]
 [ 0.49729419]
 [ 0.5010689 ]
 [-0.50652267]]
[[-0.49450539]
 [ 0.49729198]
 [ 0.50107003]
 [-0.50652636]]
[[-0.49450212]
 [ 0.49728977]
 [ 0.50107116]
 [-0.50653005]]
[[-0.49449885]
 [ 0.49728756]
 [ 0.50107228]
 [-0.50653375]]
[[-0.49449558]
 [ 0.49728535]
 [ 0.50107341]
 [-0.50653744]]
[[-0.49449231]
 [ 0.49728313]
 [ 0.50107453]
 [-0.50654114]]
[[-0.49448903]
 [ 0.49728092]
 [ 0.50107566]
 [-0.50654485]]
[[-0.49448576]
 [ 0.4972787 ]
 [ 0.50107678]
 [-0.50654855]]
[[-0.49448248]
 [ 0.49727649]
 [ 0.50107791]
 [-0.50655226]]
[[-0.49447919]
 [ 0.49727427]
 [ 0.50107903]
 [-0.50655597]]
[[-0.49447591]
 [ 0.49727205]
 [ 0.50108016]
 [-0.50655968]]
[[-0.49447262]
 [ 0.49726983]
 [ 0.50108128]
 [-0.5065634 ]]
[[-0.49446933]
 [ 0.4972676 ]
 [ 0.5010824 ]
 [-0.50656712]]
[[-0.49446604]
 [ 0.49726538]
 [ 0.50108353]
 [-0.50657084]]
[[-0.49446275]
 [ 0.49726316]
 [ 0.50108465]
 [-0.50657456]]
[[-0.49445945]
 [ 0.4972

[[-0.49230541]
 [ 0.49588486]
 [ 0.50162628]
 [-0.50902242]]
[[-0.49230039]
 [ 0.49588182]
 [ 0.50162712]
 [-0.50902812]]
[[-0.49229535]
 [ 0.49587879]
 [ 0.50162796]
 [-0.50903382]]
[[-0.49229032]
 [ 0.49587575]
 [ 0.50162879]
 [-0.50903953]]
[[-0.49228527]
 [ 0.49587271]
 [ 0.50162962]
 [-0.50904524]]
[[-0.49228023]
 [ 0.49586966]
 [ 0.50163045]
 [-0.50905096]]
[[-0.49227518]
 [ 0.49586662]
 [ 0.50163129]
 [-0.50905669]]
[[-0.49227012]
 [ 0.49586357]
 [ 0.50163212]
 [-0.50906242]]
[[-0.49226506]
 [ 0.49586053]
 [ 0.50163294]
 [-0.50906815]]
[[-0.49225999]
 [ 0.49585747]
 [ 0.50163377]
 [-0.50907389]]
[[-0.49225492]
 [ 0.49585442]
 [ 0.5016346 ]
 [-0.50907964]]
[[-0.49224985]
 [ 0.49585137]
 [ 0.50163542]
 [-0.50908539]]
[[-0.49224477]
 [ 0.49584831]
 [ 0.50163625]
 [-0.50909114]]
[[-0.49223969]
 [ 0.49584525]
 [ 0.50163707]
 [-0.5090969 ]]
[[-0.4922346 ]
 [ 0.49584219]
 [ 0.50163789]
 [-0.50910267]]
[[-0.4922295 ]
 [ 0.49583913]
 [ 0.50163871]
 [-0.50910844]]
[[-0.49222441]
 [ 0.4958

[[-0.48752267]
 [ 0.49329298]
 [ 0.50169119]
 [-0.51433546]]
[[-0.48751232]
 [ 0.49328788]
 [ 0.50168997]
 [-0.51434664]]
[[-0.48750197]
 [ 0.49328278]
 [ 0.50168874]
 [-0.51435784]]
[[-0.48749159]
 [ 0.49327767]
 [ 0.50168751]
 [-0.51436904]]
[[-0.48748121]
 [ 0.49327256]
 [ 0.50168627]
 [-0.51438026]]
[[-0.48747081]
 [ 0.49326744]
 [ 0.50168502]
 [-0.51439149]]
[[-0.4874604 ]
 [ 0.49326232]
 [ 0.50168377]
 [-0.51440273]]
[[-0.48744998]
 [ 0.49325719]
 [ 0.50168251]
 [-0.51441399]]
[[-0.48743954]
 [ 0.49325206]
 [ 0.50168125]
 [-0.51442526]]
[[-0.48742909]
 [ 0.49324693]
 [ 0.50167998]
 [-0.51443654]]
[[-0.48741862]
 [ 0.49324178]
 [ 0.5016787 ]
 [-0.51444783]]
[[-0.48740814]
 [ 0.49323664]
 [ 0.50167741]
 [-0.51445914]]
[[-0.48739765]
 [ 0.49323149]
 [ 0.50167612]
 [-0.51447046]]
[[-0.48738715]
 [ 0.49322633]
 [ 0.50167482]
 [-0.51448179]]
[[-0.48737663]
 [ 0.49322117]
 [ 0.50167352]
 [-0.51449313]]
[[-0.4873661 ]
 [ 0.493216  ]
 [ 0.5016722 ]
 [-0.51450449]]
[[-0.48735555]
 [ 0.4932

[[-0.47629229]
 [ 0.48830757]
 [ 0.49836987]
 [-0.52540937]]
[[-0.47626531]
 [ 0.48829624]
 [ 0.4983588 ]
 [-0.52543335]]
[[-0.4762383 ]
 [ 0.48828489]
 [ 0.4983477 ]
 [-0.52545735]]
[[-0.47621123]
 [ 0.48827353]
 [ 0.49833657]
 [-0.52548137]]
[[-0.47618413]
 [ 0.48826214]
 [ 0.49832542]
 [-0.52550542]]
[[-0.47615698]
 [ 0.48825074]
 [ 0.49831424]
 [-0.5255295 ]]
[[-0.47612978]
 [ 0.48823933]
 [ 0.49830303]
 [-0.52555361]]
[[-0.47610255]
 [ 0.48822789]
 [ 0.49829179]
 [-0.52557774]]
[[-0.47607526]
 [ 0.48821644]
 [ 0.49828053]
 [-0.5256019 ]]
[[-0.47604794]
 [ 0.48820497]
 [ 0.49826924]
 [-0.52562609]]
[[-0.47602057]
 [ 0.48819348]
 [ 0.49825793]
 [-0.5256503 ]]
[[-0.47599315]
 [ 0.48818198]
 [ 0.49824659]
 [-0.52567454]]
[[-0.47596569]
 [ 0.48817045]
 [ 0.49823522]
 [-0.52569881]]
[[-0.47593819]
 [ 0.48815891]
 [ 0.49822382]
 [-0.5257231 ]]
[[-0.47591064]
 [ 0.48814736]
 [ 0.4982124 ]
 [-0.52574742]]
[[-0.47588305]
 [ 0.48813578]
 [ 0.49820095]
 [-0.52577177]]
[[-0.47585541]
 [ 0.4881

[[-0.44770313]
 [ 0.47641644]
 [ 0.48502514]
 [-0.54586468]]
[[-0.44762624]
 [ 0.47638439]
 [ 0.48498887]
 [-0.54591078]]
[[-0.4475492 ]
 [ 0.47635228]
 [ 0.48495254]
 [-0.54595694]]
[[-0.44747203]
 [ 0.47632011]
 [ 0.48491615]
 [-0.54600315]]
[[-0.44739472]
 [ 0.47628788]
 [ 0.4848797 ]
 [-0.54604941]]
[[-0.44731728]
 [ 0.47625559]
 [ 0.48484319]
 [-0.54609572]]
[[-0.44723969]
 [ 0.47622324]
 [ 0.48480662]
 [-0.54614209]]
[[-0.44716196]
 [ 0.47619084]
 [ 0.48476999]
 [-0.54618851]]
[[-0.4470841 ]
 [ 0.47615837]
 [ 0.48473329]
 [-0.54623498]]
[[-0.44700609]
 [ 0.47612585]
 [ 0.48469654]
 [-0.54628151]]
[[-0.44692795]
 [ 0.47609327]
 [ 0.48465973]
 [-0.54632809]]
[[-0.44684966]
 [ 0.47606062]
 [ 0.48462286]
 [-0.54637473]]
[[-0.44677124]
 [ 0.47602792]
 [ 0.48458592]
 [-0.54642142]]
[[-0.44669267]
 [ 0.47599516]
 [ 0.48454893]
 [-0.54646816]]
[[-0.44661397]
 [ 0.47596234]
 [ 0.48451187]
 [-0.54651496]]
[[-0.44653512]
 [ 0.47592946]
 [ 0.48447476]
 [-0.54656181]]
[[-0.44645613]
 [ 0.4758

 [-0.5604144 ]]
[[-0.42118221]
 [ 0.46530514]
 [ 0.47278895]
 [-0.56047723]]
[[-0.42105992]
 [ 0.46525358]
 [ 0.47273351]
 [-0.56054012]]
[[-0.42093744]
 [ 0.46520194]
 [ 0.47267798]
 [-0.56060308]]
[[-0.42081477]
 [ 0.46515022]
 [ 0.47262238]
 [-0.5606661 ]]
[[-0.42069191]
 [ 0.46509841]
 [ 0.47256669]
 [-0.5607292 ]]
[[-0.42056885]
 [ 0.46504651]
 [ 0.47251092]
 [-0.56079236]]
[[-0.4204456 ]
 [ 0.46499453]
 [ 0.47245507]
 [-0.56085559]]
[[-0.42032215]
 [ 0.46494246]
 [ 0.47239914]
 [-0.56091888]]
[[-0.42019852]
 [ 0.46489031]
 [ 0.47234313]
 [-0.56098224]]
[[-0.42007468]
 [ 0.46483808]
 [ 0.47228704]
 [-0.56104567]]
[[-0.41995066]
 [ 0.46478576]
 [ 0.47223086]
 [-0.56110916]]
[[-0.41982644]
 [ 0.46473335]
 [ 0.4721746 ]
 [-0.56117273]]
[[-0.41970202]
 [ 0.46468086]
 [ 0.47211826]
 [-0.56123635]]
[[-0.41957742]
 [ 0.46462828]
 [ 0.47206184]
 [-0.56130005]]
[[-0.41945261]
 [ 0.46457561]
 [ 0.47200533]
 [-0.56136381]]
[[-0.41932762]
 [ 0.46452286]
 [ 0.47194875]
 [-0.56142764]]
[[-0.419

[[-0.37910495]
 [ 0.44732644]
 [ 0.45388978]
 [-0.58049125]]
[[-0.37893068]
 [ 0.44725094]
 [ 0.45381178]
 [-0.58056778]]
[[-0.37875627]
 [ 0.44717537]
 [ 0.45373371]
 [-0.58064431]]
[[-0.37858171]
 [ 0.44709972]
 [ 0.45365558]
 [-0.58072086]]
[[-0.378407  ]
 [ 0.44702401]
 [ 0.45357738]
 [-0.58079742]]
[[-0.37823215]
 [ 0.44694822]
 [ 0.45349911]
 [-0.58087398]]
[[-0.37805715]
 [ 0.44687236]
 [ 0.45342079]
 [-0.58095056]]
[[-0.377882  ]
 [ 0.44679644]
 [ 0.45334239]
 [-0.58102715]]
[[-0.37770671]
 [ 0.44672043]
 [ 0.45326393]
 [-0.58110375]]
[[-0.37753127]
 [ 0.44664436]
 [ 0.45318541]
 [-0.58118036]]
[[-0.37735569]
 [ 0.44656822]
 [ 0.45310682]
 [-0.58125697]]
[[-0.37717997]
 [ 0.44649201]
 [ 0.45302817]
 [-0.5813336 ]]
[[-0.37700411]
 [ 0.44641572]
 [ 0.45294945]
 [-0.58141023]]
[[-0.3768281 ]
 [ 0.44633937]
 [ 0.45287068]
 [-0.58148687]]
[[-0.37665195]
 [ 0.44626295]
 [ 0.45279183]
 [-0.58156351]]
[[-0.37647565]
 [ 0.44618645]
 [ 0.45271293]
 [-0.58164017]]
[[-0.37629922]
 [ 0.4461

[[-0.33720647]
 [ 0.42897475]
 [ 0.43516465]
 [-0.59721688]]
[[-0.33701344]
 [ 0.42888949]
 [ 0.43507872]
 [-0.59728528]]
[[-0.3368204 ]
 [ 0.42880422]
 [ 0.4349928 ]
 [-0.59735361]]
[[-0.33662734]
 [ 0.42871895]
 [ 0.43490687]
 [-0.59742184]]
[[-0.33643428]
 [ 0.42863366]
 [ 0.43482095]
 [-0.59748999]]
[[-0.33624121]
 [ 0.42854837]
 [ 0.43473503]
 [-0.59755806]]
[[-0.33604813]
 [ 0.42846307]
 [ 0.43464912]
 [-0.59762604]]
[[-0.33585504]
 [ 0.42837776]
 [ 0.4345632 ]
 [-0.59769393]]
[[-0.33566194]
 [ 0.42829244]
 [ 0.43447729]
 [-0.59776173]]
[[-0.33546884]
 [ 0.42820712]
 [ 0.43439139]
 [-0.59782944]]
[[-0.33527574]
 [ 0.42812179]
 [ 0.43430548]
 [-0.59789707]]
[[-0.33508262]
 [ 0.42803645]
 [ 0.43421958]
 [-0.5979646 ]]
[[-0.33488951]
 [ 0.42795111]
 [ 0.43413369]
 [-0.59803205]]
[[-0.33469639]
 [ 0.42786577]
 [ 0.4340478 ]
 [-0.59809941]]
[[-0.33450327]
 [ 0.42778041]
 [ 0.43396192]
 [-0.59816668]]
[[-0.33431014]
 [ 0.42769506]
 [ 0.43387604]
 [-0.59823385]]
[[-0.33411701]
 [ 0.4276

[[-0.25435533]
 [ 0.3921677 ]
 [ 0.39946605]
 [-0.61520591]]
[[-0.25421066]
 [ 0.39210228]
 [ 0.39940654]
 [-0.61520795]]
[[-0.25406616]
 [ 0.39203692]
 [ 0.39934711]
 [-0.61520982]]
[[-0.25392182]
 [ 0.39197161]
 [ 0.39928776]
 [-0.61521154]]
[[-0.25377765]
 [ 0.39190637]
 [ 0.39922849]
 [-0.61521308]]
[[-0.25363365]
 [ 0.39184119]
 [ 0.39916929]
 [-0.61521446]]
[[-0.25348981]
 [ 0.39177607]
 [ 0.39911017]
 [-0.61521568]]
[[-0.25334615]
 [ 0.39171102]
 [ 0.39905113]
 [-0.61521673]]
[[-0.25320265]
 [ 0.39164602]
 [ 0.39899217]
 [-0.61521762]]
[[-0.25305932]
 [ 0.39158108]
 [ 0.39893328]
 [-0.61521833]]
[[-0.25291616]
 [ 0.3915162 ]
 [ 0.39887447]
 [-0.61521889]]
[[-0.25277317]
 [ 0.39145138]
 [ 0.39881574]
 [-0.61521928]]
[[-0.25263035]
 [ 0.39138663]
 [ 0.39875708]
 [-0.6152195 ]]
[[-0.25248769]
 [ 0.39132193]
 [ 0.3986985 ]
 [-0.61521956]]
[[-0.25234521]
 [ 0.39125729]
 [ 0.39864   ]
 [-0.61521945]]
[[-0.25220289]
 [ 0.39119272]
 [ 0.39858158]
 [-0.61521917]]
[[-0.25206075]
 [ 0.3911

[[-0.21222765]
 [ 0.37097535]
 [ 0.38156877]
 [-0.60331956]]
[[-0.21214996]
 [ 0.37092535]
 [ 0.38152927]
 [-0.60324973]]
[[-0.21207247]
 [ 0.37087537]
 [ 0.38148977]
 [-0.60317966]]
[[-0.21199515]
 [ 0.37082541]
 [ 0.38145029]
 [-0.60310935]]
[[-0.21191803]
 [ 0.37077545]
 [ 0.38141081]
 [-0.6030388 ]]
[[-0.21184108]
 [ 0.37072551]
 [ 0.38137135]
 [-0.602968  ]]
[[-0.21176433]
 [ 0.37067558]
 [ 0.3813319 ]
 [-0.60289696]]
[[-0.21168775]
 [ 0.37062566]
 [ 0.38129245]
 [-0.60282568]]
[[-0.21161136]
 [ 0.37057576]
 [ 0.38125301]
 [-0.60275416]]
[[-0.21153516]
 [ 0.37052587]
 [ 0.38121358]
 [-0.6026824 ]]
[[-0.21145914]
 [ 0.37047599]
 [ 0.38117416]
 [-0.60261039]]
[[-0.21138331]
 [ 0.37042612]
 [ 0.38113474]
 [-0.60253814]]
[[-0.21130766]
 [ 0.37037627]
 [ 0.38109534]
 [-0.60246564]]
[[-0.21123219]
 [ 0.37032642]
 [ 0.38105593]
 [-0.6023929 ]]
[[-0.21115691]
 [ 0.37027659]
 [ 0.38101654]
 [-0.60231991]]
[[-0.21108182]
 [ 0.37022676]
 [ 0.38097715]
 [-0.60224667]]
[[-0.21100691]
 [ 0.3701

[[-0.19590171]
 [ 0.33178059]
 [ 0.33890778]
 [-0.49504022]]
[[-0.19590509]
 [ 0.33167267]
 [ 0.33877342]
 [-0.49473461]]
[[-0.19590843]
 [ 0.33156448]
 [ 0.33863879]
 [-0.49442861]]
[[-0.19591174]
 [ 0.33145601]
 [ 0.33850387]
 [-0.49412223]]
[[-0.195915  ]
 [ 0.33134727]
 [ 0.33836869]
 [-0.49381547]]
[[-0.19591823]
 [ 0.33123824]
 [ 0.33823322]
 [-0.49350832]]
[[-0.19592141]
 [ 0.33112893]
 [ 0.33809749]
 [-0.49320078]]
[[-0.19592456]
 [ 0.33101935]
 [ 0.33796147]
 [-0.49289287]]
[[-0.19592766]
 [ 0.33090948]
 [ 0.33782519]
 [-0.49258457]]
[[-0.19593072]
 [ 0.33079933]
 [ 0.33768863]
 [-0.4922759 ]]
[[-0.19593373]
 [ 0.3306889 ]
 [ 0.33755179]
 [-0.49196685]]
[[-0.1959367 ]
 [ 0.33057819]
 [ 0.33741468]
 [-0.49165742]]
[[-0.19593963]
 [ 0.33046719]
 [ 0.3372773 ]
 [-0.49134761]]
[[-0.1959425 ]
 [ 0.33035591]
 [ 0.33713964]
 [-0.49103743]]
[[-0.19594534]
 [ 0.33024435]
 [ 0.33700171]
 [-0.49072687]]
[[-0.19594812]
 [ 0.3301325 ]
 [ 0.33686351]
 [-0.49041594]]
[[-0.19595085]
 [ 0.3300

[[-0.17553419]
 [ 0.22965744]
 [ 0.22971391]
 [-0.29359858]]
[[-0.17546875]
 [ 0.22948723]
 [ 0.22954266]
 [-0.2933309 ]]
[[-0.17540327]
 [ 0.22931717]
 [ 0.22937157]
 [-0.29306356]]
[[-0.17533777]
 [ 0.22914724]
 [ 0.22920064]
 [-0.29279656]]
[[-0.17527222]
 [ 0.22897747]
 [ 0.22902985]
 [-0.2925299 ]]
[[-0.17520665]
 [ 0.22880784]
 [ 0.22885923]
 [-0.29226359]]
[[-0.17514105]
 [ 0.22863836]
 [ 0.22868875]
 [-0.29199762]]
[[-0.17507541]
 [ 0.22846903]
 [ 0.22851844]
 [-0.291732  ]]
[[-0.17500975]
 [ 0.22829985]
 [ 0.22834828]
 [-0.29146671]]
[[-0.17494405]
 [ 0.22813081]
 [ 0.22817827]
 [-0.29120177]]
[[-0.17487833]
 [ 0.22796192]
 [ 0.22800842]
 [-0.29093717]]
[[-0.17481257]
 [ 0.22779318]
 [ 0.22783873]
 [-0.29067292]]
[[-0.17474679]
 [ 0.22762459]
 [ 0.22766919]
 [-0.290409  ]]
[[-0.17468097]
 [ 0.22745615]
 [ 0.22749981]
 [-0.29014543]]
[[-0.17461513]
 [ 0.22728786]
 [ 0.22733058]
 [-0.2898822 ]]
[[-0.17454926]
 [ 0.22711972]
 [ 0.22716152]
 [-0.28961931]]
[[-0.17448336]
 [ 0.2269

[[-0.14912019]
 [ 0.17345018]
 [ 0.17338147]
 [-0.21035087]]
[[-0.14906047]
 [ 0.17334286]
 [ 0.17327412]
 [-0.21020035]]
[[-0.14900079]
 [ 0.17323567]
 [ 0.17316691]
 [-0.21005004]]
[[-0.14894115]
 [ 0.17312861]
 [ 0.17305983]
 [-0.20989994]]
[[-0.14888155]
 [ 0.17302169]
 [ 0.17295288]
 [-0.20975006]]
[[-0.14882198]
 [ 0.1729149 ]
 [ 0.17284606]
 [-0.20960039]]
[[-0.14876245]
 [ 0.17280824]
 [ 0.17273937]
 [-0.20945093]]
[[-0.14870296]
 [ 0.17270171]
 [ 0.17263282]
 [-0.20930169]]
[[-0.1486435 ]
 [ 0.17259531]
 [ 0.1725264 ]
 [-0.20915265]]
[[-0.14858409]
 [ 0.17248905]
 [ 0.17242011]
 [-0.20900383]]
[[-0.14852471]
 [ 0.17238291]
 [ 0.17231395]
 [-0.20885522]]
[[-0.14846537]
 [ 0.17227691]
 [ 0.17220792]
 [-0.20870682]]
[[-0.14840606]
 [ 0.17217104]
 [ 0.17210203]
 [-0.20855863]]
[[-0.1483468 ]
 [ 0.1720653 ]
 [ 0.17199626]
 [-0.20841065]]
[[-0.14828757]
 [ 0.17195969]
 [ 0.17189063]
 [-0.20826287]]
[[-0.14822839]
 [ 0.1718542 ]
 [ 0.17178513]
 [-0.20811531]]
[[-0.14816924]
 [ 0.1717

[[-0.11984442]
 [ 0.12705753]
 [ 0.12699722]
 [-0.14773565]]
[[-0.11980628]
 [ 0.12700367]
 [ 0.12694339]
 [-0.14766568]]
[[-0.11976816]
 [ 0.12694987]
 [ 0.12688962]
 [-0.14759578]]
[[-0.11973008]
 [ 0.12689612]
 [ 0.12683589]
 [-0.14752596]]
[[-0.11969202]
 [ 0.12684243]
 [ 0.12678222]
 [-0.14745622]]
[[-0.11965399]
 [ 0.12678879]
 [ 0.12672861]
 [-0.14738656]]
[[-0.11961599]
 [ 0.12673521]
 [ 0.12667505]
 [-0.14731697]]
[[-0.11957802]
 [ 0.12668168]
 [ 0.12662154]
 [-0.14724746]]
[[-0.11954008]
 [ 0.1266282 ]
 [ 0.12656809]
 [-0.14717803]]
[[-0.11950217]
 [ 0.12657478]
 [ 0.12651469]
 [-0.14710867]]
[[-0.11946428]
 [ 0.12652141]
 [ 0.12646135]
 [-0.14703938]]
[[-0.11942642]
 [ 0.1264681 ]
 [ 0.12640806]
 [-0.14697018]]
[[-0.1193886 ]
 [ 0.12641484]
 [ 0.12635482]
 [-0.14690104]]
[[-0.11935079]
 [ 0.12636163]
 [ 0.12630164]
 [-0.14683199]]
[[-0.11931302]
 [ 0.12630848]
 [ 0.12624851]
 [-0.14676301]]
[[-0.11927528]
 [ 0.12625538]
 [ 0.12619543]
 [-0.1466941 ]]
[[-0.11923756]
 [ 0.1262

In [10]:
print("Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

print("\nOutput from neural network after 10,000 epochs: ",end='')
print(*predicted_output)

Final hidden weights: [3.05538351 5.40254931] [3.05377519 5.39252761]
Final hidden bias: [-4.62689434 -2.04612389]
Final output weights: [-6.73208119] [6.31159581]
Final output bias: [-2.80863382]

Output from neural network after 10,000 epochs: [0.10421431] [0.89393073] [0.89398073] [0.12092494]
