In [1]:
import numpy as np

In [2]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [11]:
#Input datasets
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])

#expected_output = np.array([[0],[1],[1],[0]]) #XOR

expected_output = np.array([[1],[ 1],[1],[0]]) #NAND

                         #[0.99480946] [0.96879777] [0.96770812] [0.04935737]
                         #[1,1,1,0]

In [12]:
epochs = 10000
lr = 0.1
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2,2,1

In [13]:
#Random weights and bias initialization
hidden_weights = np.random.uniform(size=(inputLayerNeurons,hiddenLayerNeurons))
hidden_bias =np.random.uniform(size=(1,hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons,outputLayerNeurons))
output_bias = np.random.uniform(size=(1,outputLayerNeurons))

In [14]:
print("Initial hidden weights: ",end='')
print(*hidden_weights)
print("Initial hidden biases: ",end='')
print(*hidden_bias)
print("Initial output weights: ",end='')
print(*output_weights)
print("Initial output biases: ",end='')
print(*output_bias)

Initial hidden weights: [0.5993976  0.79947924] [0.20786994 0.51485228]
Initial hidden biases: [0.23548173 0.63794404]
Initial output weights: [0.50008815] [0.94216767]
Initial output biases: [0.10858083]


In [15]:
#Training algorithm

In [16]:
for _ in range(epochs):
    #Forward Propagation
    hidden_layer_activation = np.dot(inputs,hidden_weights)
    hidden_layer_activation += hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output,output_weights)
    output_layer_activation += output_bias
    predicted_output = sigmoid(output_layer_activation)

    #Backpropagation
    error = expected_output - predicted_output
    print(error)    
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    #Updating Weights and Biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * lr

[[ 0.26808122]
 [ 0.2443031 ]
 [ 0.22817258]
 [-0.78640449]]
[[ 0.26823879]
 [ 0.24453498]
 [ 0.22843443]
 [-0.78610547]]
[[ 0.26839204]
 [ 0.24476238]
 [ 0.22869181]
 [-0.78581091]]
[[ 0.26854105]
 [ 0.24498537]
 [ 0.22894478]
 [-0.78552073]]
[[ 0.2686859 ]
 [ 0.24520403]
 [ 0.22919343]
 [-0.78523488]]
[[ 0.26882667]
 [ 0.24541843]
 [ 0.22943783]
 [-0.78495326]]
[[ 0.26896344]
 [ 0.24562867]
 [ 0.22967805]
 [-0.78467582]]
[[ 0.26909628]
 [ 0.24583481]
 [ 0.22991417]
 [-0.78440247]]
[[ 0.26922529]
 [ 0.24603693]
 [ 0.23014627]
 [-0.78413315]]
[[ 0.26935053]
 [ 0.2462351 ]
 [ 0.23037441]
 [-0.78386779]]
[[ 0.26947207]
 [ 0.2464294 ]
 [ 0.23059867]
 [-0.78360632]]
[[ 0.26959   ]
 [ 0.2466199 ]
 [ 0.23081911]
 [-0.78334867]]
[[ 0.26970438]
 [ 0.24680668]
 [ 0.23103581]
 [-0.78309478]]
[[ 0.26981529]
 [ 0.2469898 ]
 [ 0.23124883]
 [-0.78284458]]
[[ 0.2699228 ]
 [ 0.24716933]
 [ 0.23145825]
 [-0.782598  ]]
[[ 0.27002698]
 [ 0.24734534]
 [ 0.23166413]
 [-0.78235498]]
[[ 0.27012789]
 [ 0.2475

[[ 0.25931749]
 [ 0.25649304]
 [ 0.24950807]
 [-0.75242016]]
[[ 0.25929496]
 [ 0.25648857]
 [ 0.24950886]
 [-0.75240597]]
[[ 0.25927245]
 [ 0.25648409]
 [ 0.24950961]
 [-0.75239183]]
[[ 0.25924996]
 [ 0.25647959]
 [ 0.24951032]
 [-0.75237774]]
[[ 0.25922748]
 [ 0.25647509]
 [ 0.24951099]
 [-0.75236369]]
[[ 0.25920501]
 [ 0.25647058]
 [ 0.24951161]
 [-0.75234969]]
[[ 0.25918255]
 [ 0.25646605]
 [ 0.2495122 ]
 [-0.75233574]]
[[ 0.25916011]
 [ 0.25646152]
 [ 0.24951274]
 [-0.75232184]]
[[ 0.25913768]
 [ 0.25645698]
 [ 0.24951325]
 [-0.75230798]]
[[ 0.25911526]
 [ 0.25645243]
 [ 0.24951371]
 [-0.75229417]]
[[ 0.25909286]
 [ 0.25644787]
 [ 0.24951413]
 [-0.75228041]]
[[ 0.25907047]
 [ 0.2564433 ]
 [ 0.24951452]
 [-0.75226669]]
[[ 0.25904809]
 [ 0.25643873]
 [ 0.24951486]
 [-0.75225302]]
[[ 0.25902573]
 [ 0.25643414]
 [ 0.24951516]
 [-0.75223939]]
[[ 0.25900337]
 [ 0.25642954]
 [ 0.24951542]
 [-0.75222581]]
[[ 0.25898103]
 [ 0.25642494]
 [ 0.24951564]
 [-0.75221228]]
[[ 0.25895871]
 [ 0.2564

[[ 0.24783216]
 [ 0.2552498 ]
 [ 0.24691185]
 [-0.74565845]]
[[ 0.24779899]
 [ 0.25525657]
 [ 0.24690567]
 [-0.74562443]]
[[ 0.24776574]
 [ 0.25526342]
 [ 0.24689953]
 [-0.74559018]]
[[ 0.24773241]
 [ 0.25527038]
 [ 0.24689343]
 [-0.7455557 ]]
[[ 0.24769899]
 [ 0.25527744]
 [ 0.24688738]
 [-0.74552099]]
[[ 0.2476655 ]
 [ 0.25528459]
 [ 0.24688137]
 [-0.74548604]]
[[ 0.24763192]
 [ 0.25529185]
 [ 0.24687541]
 [-0.74545087]]
[[ 0.24759825]
 [ 0.2552992 ]
 [ 0.24686949]
 [-0.74541546]]
[[ 0.24756451]
 [ 0.25530666]
 [ 0.24686362]
 [-0.74537981]]
[[ 0.24753068]
 [ 0.25531422]
 [ 0.24685779]
 [-0.74534393]]
[[ 0.24749676]
 [ 0.25532188]
 [ 0.24685201]
 [-0.7453078 ]]
[[ 0.24746276]
 [ 0.25532964]
 [ 0.24684627]
 [-0.74527144]]
[[ 0.24742868]
 [ 0.25533751]
 [ 0.24684058]
 [-0.74523483]]
[[ 0.2473945 ]
 [ 0.25534548]
 [ 0.24683494]
 [-0.74519798]]
[[ 0.24736025]
 [ 0.25535355]
 [ 0.24682935]
 [-0.74516089]]
[[ 0.2473259 ]
 [ 0.25536173]
 [ 0.24682381]
 [-0.74512354]]
[[ 0.24729147]
 [ 0.2553

[[ 0.20776826]
 [ 0.2776989 ]
 [ 0.25623323]
 [-0.67652948]]
[[ 0.20760206]
 [ 0.27777247]
 [ 0.25627003]
 [-0.67626061]]
[[ 0.20743543]
 [ 0.27784596]
 [ 0.25630676]
 [-0.67599127]]
[[ 0.20726838]
 [ 0.27791937]
 [ 0.25634341]
 [-0.67572144]]
[[ 0.2071009 ]
 [ 0.27799271]
 [ 0.25637999]
 [-0.67545112]]
[[ 0.20693299]
 [ 0.27806597]
 [ 0.2564165 ]
 [-0.67518033]]
[[ 0.20676465]
 [ 0.27813914]
 [ 0.25645293]
 [-0.67490905]]
[[ 0.20659589]
 [ 0.27821223]
 [ 0.25648928]
 [-0.67463729]]
[[ 0.2064267 ]
 [ 0.27828523]
 [ 0.25652555]
 [-0.67436505]]
[[ 0.20625709]
 [ 0.27835815]
 [ 0.25656174]
 [-0.67409233]]
[[ 0.20608706]
 [ 0.27843098]
 [ 0.25659785]
 [-0.67381912]]
[[ 0.2059166 ]
 [ 0.27850372]
 [ 0.25663388]
 [-0.67354543]]
[[ 0.20574572]
 [ 0.27857636]
 [ 0.25666982]
 [-0.67327126]]
[[ 0.20557442]
 [ 0.27864891]
 [ 0.25670568]
 [-0.6729966 ]]
[[ 0.20540269]
 [ 0.27872136]
 [ 0.25674145]
 [-0.67272146]]
[[ 0.20523055]
 [ 0.27879371]
 [ 0.25677713]
 [-0.67244584]]
[[ 0.20505798]
 [ 0.2788

[[ 0.11003738]
 [ 0.27190192]
 [ 0.25048755]
 [-0.50351424]]
[[ 0.10983947]
 [ 0.27175642]
 [ 0.25040408]
 [-0.50304997]]
[[ 0.10964184]
 [ 0.2716104 ]
 [ 0.25032025]
 [-0.50258557]]
[[ 0.1094445 ]
 [ 0.27146386]
 [ 0.25023606]
 [-0.50212106]]
[[ 0.10924744]
 [ 0.2713168 ]
 [ 0.25015151]
 [-0.50165643]]
[[ 0.10905068]
 [ 0.27116923]
 [ 0.2500666 ]
 [-0.50119168]]
[[ 0.1088542 ]
 [ 0.27102114]
 [ 0.24998133]
 [-0.50072683]]
[[ 0.10865801]
 [ 0.27087254]
 [ 0.24989571]
 [-0.50026186]]
[[ 0.10846211]
 [ 0.27072343]
 [ 0.24980972]
 [-0.49979679]]
[[ 0.1082665 ]
 [ 0.27057382]
 [ 0.24972337]
 [-0.49933161]]
[[ 0.10807117]
 [ 0.2704237 ]
 [ 0.24963666]
 [-0.49886633]]
[[ 0.10787614]
 [ 0.27027309]
 [ 0.2495496 ]
 [-0.49840096]]
[[ 0.1076814 ]
 [ 0.27012197]
 [ 0.24946217]
 [-0.49793548]]
[[ 0.10748696]
 [ 0.26997036]
 [ 0.24937438]
 [-0.49746992]]
[[ 0.1072928 ]
 [ 0.26981825]
 [ 0.24928624]
 [-0.49700427]]
[[ 0.10709894]
 [ 0.26966566]
 [ 0.24919773]
 [-0.49653853]]
[[ 0.10690537]
 [ 0.2695

[[ 0.03882764]
 [ 0.16060409]
 [ 0.1612616 ]
 [-0.2637813 ]]
[[ 0.03877969]
 [ 0.16047432]
 [ 0.16113634]
 [-0.26354744]]
[[ 0.03873184]
 [ 0.16034473]
 [ 0.16101123]
 [-0.26331395]]
[[ 0.03868411]
 [ 0.16021531]
 [ 0.16088627]
 [-0.26308084]]
[[ 0.03863648]
 [ 0.16008608]
 [ 0.16076147]
 [-0.26284812]]
[[ 0.03858896]
 [ 0.15995703]
 [ 0.16063682]
 [-0.26261577]]
[[ 0.03854154]
 [ 0.15982816]
 [ 0.16051232]
 [-0.2623838 ]]
[[ 0.03849424]
 [ 0.15969947]
 [ 0.16038798]
 [-0.26215221]]
[[ 0.03844704]
 [ 0.15957096]
 [ 0.16026379]
 [-0.26192099]]
[[ 0.03839995]
 [ 0.15944263]
 [ 0.16013976]
 [-0.26169016]]
[[ 0.03835296]
 [ 0.15931448]
 [ 0.16001588]
 [-0.26145969]]
[[ 0.03830608]
 [ 0.15918651]
 [ 0.15989215]
 [-0.26122961]]
[[ 0.03825931]
 [ 0.15905872]
 [ 0.15976858]
 [-0.2609999 ]]
[[ 0.03821264]
 [ 0.15893111]
 [ 0.15964516]
 [-0.26077056]]
[[ 0.03816608]
 [ 0.15880367]
 [ 0.15952189]
 [-0.26054159]]
[[ 0.03811962]
 [ 0.15867642]
 [ 0.15939878]
 [-0.260313  ]]
[[ 0.03807327]
 [ 0.1585

[[ 0.01948925]
 [ 0.09723298]
 [ 0.09864167]
 [-0.15502035]]
[[ 0.01947771]
 [ 0.0971873 ]
 [ 0.09859597]
 [-0.15494517]]
[[ 0.01946617]
 [ 0.09714166]
 [ 0.09855033]
 [-0.15487007]]
[[ 0.01945465]
 [ 0.09709607]
 [ 0.09850473]
 [-0.15479506]]
[[ 0.01944315]
 [ 0.09705053]
 [ 0.09845919]
 [-0.15472013]]
[[ 0.01943166]
 [ 0.09700504]
 [ 0.09841369]
 [-0.15464529]]
[[ 0.01942019]
 [ 0.0969596 ]
 [ 0.09836825]
 [-0.15457054]]
[[ 0.01940873]
 [ 0.09691421]
 [ 0.09832285]
 [-0.15449587]]
[[ 0.01939729]
 [ 0.09686887]
 [ 0.0982775 ]
 [-0.15442129]]
[[ 0.01938587]
 [ 0.09682358]
 [ 0.0982322 ]
 [-0.15434679]]
[[ 0.01937445]
 [ 0.09677834]
 [ 0.09818695]
 [-0.15427237]]
[[ 0.01936306]
 [ 0.09673315]
 [ 0.09814175]
 [-0.15419805]]
[[ 0.01935168]
 [ 0.09668801]
 [ 0.0980966 ]
 [-0.1541238 ]]
[[ 0.01934031]
 [ 0.09664292]
 [ 0.0980515 ]
 [-0.15404964]]
[[ 0.01932896]
 [ 0.09659787]
 [ 0.09800645]
 [-0.15397557]]
[[ 0.01931763]
 [ 0.09655288]
 [ 0.09796144]
 [-0.15390158]]
[[ 0.0193063 ]
 [ 0.0965

[[ 0.01409032]
 [ 0.07462016]
 [ 0.0759881 ]
 [-0.11822702]]
[[ 0.01408488]
 [ 0.07459608]
 [ 0.07596393]
 [-0.11818824]]
[[ 0.01407945]
 [ 0.07457201]
 [ 0.07593978]
 [-0.11814949]]
[[ 0.01407403]
 [ 0.07454796]
 [ 0.07591566]
 [-0.11811077]]
[[ 0.01406861]
 [ 0.07452393]
 [ 0.07589155]
 [-0.11807208]]
[[ 0.01406319]
 [ 0.07449992]
 [ 0.07586746]
 [-0.11803343]]
[[ 0.01405778]
 [ 0.07447593]
 [ 0.07584339]
 [-0.1179948 ]]
[[ 0.01405238]
 [ 0.07445196]
 [ 0.07581934]
 [-0.11795621]]
[[ 0.01404698]
 [ 0.07442801]
 [ 0.07579531]
 [-0.11791765]]
[[ 0.01404158]
 [ 0.07440408]
 [ 0.0757713 ]
 [-0.11787912]]
[[ 0.01403619]
 [ 0.07438017]
 [ 0.07574731]
 [-0.11784063]]
[[ 0.01403081]
 [ 0.07435627]
 [ 0.07572333]
 [-0.11780216]]
[[ 0.01402543]
 [ 0.0743324 ]
 [ 0.07569938]
 [-0.11776373]]
[[ 0.01402005]
 [ 0.07430854]
 [ 0.07567544]
 [-0.11772533]]
[[ 0.01401468]
 [ 0.07428471]
 [ 0.07565153]
 [-0.11768696]]
[[ 0.01400932]
 [ 0.07426089]
 [ 0.07562763]
 [-0.11764862]]
[[ 0.01400395]
 [ 0.0742

[[ 0.01157468]
 [ 0.06316914]
 [ 0.06449128]
 [-0.09987378]]
[[ 0.0115713 ]
 [ 0.06315334]
 [ 0.0644754 ]
 [-0.09984856]]
[[ 0.01156792]
 [ 0.06313754]
 [ 0.06445953]
 [-0.09982335]]
[[ 0.01156454]
 [ 0.06312176]
 [ 0.06444367]
 [-0.09979816]]
[[ 0.01156117]
 [ 0.06310598]
 [ 0.06442782]
 [-0.09977299]]
[[ 0.0115578 ]
 [ 0.06309022]
 [ 0.06441198]
 [-0.09974783]]
[[ 0.01155443]
 [ 0.06307446]
 [ 0.06439615]
 [-0.0997227 ]]
[[ 0.01155106]
 [ 0.06305872]
 [ 0.06438033]
 [-0.09969757]]
[[ 0.0115477 ]
 [ 0.06304298]
 [ 0.06436452]
 [-0.09967247]]
[[ 0.01154434]
 [ 0.06302726]
 [ 0.06434873]
 [-0.09964737]]
[[ 0.01154098]
 [ 0.06301154]
 [ 0.06433294]
 [-0.0996223 ]]
[[ 0.01153762]
 [ 0.06299584]
 [ 0.06431716]
 [-0.09959724]]
[[ 0.01153427]
 [ 0.06298014]
 [ 0.06430139]
 [-0.0995722 ]]
[[ 0.01153091]
 [ 0.06296446]
 [ 0.06428563]
 [-0.09954718]]
[[ 0.01152756]
 [ 0.06294878]
 [ 0.06426988]
 [-0.09952217]]
[[ 0.01152422]
 [ 0.06293312]
 [ 0.06425414]
 [-0.09949717]]
[[ 0.01152087]
 [ 0.0629

[[ 0.00981456]
 [ 0.05478545]
 [ 0.05606344]
 [-0.08653475]]
[[ 0.00981231]
 [ 0.05477452]
 [ 0.05605244]
 [-0.0865174 ]]
[[ 0.00981006]
 [ 0.05476359]
 [ 0.05604145]
 [-0.08650006]]
[[ 0.00980781]
 [ 0.05475267]
 [ 0.05603046]
 [-0.08648273]]
[[ 0.00980556]
 [ 0.05474175]
 [ 0.05601948]
 [-0.08646541]]
[[ 0.00980331]
 [ 0.05473084]
 [ 0.05600851]
 [-0.0864481 ]]
[[ 0.00980106]
 [ 0.05471993]
 [ 0.05599754]
 [-0.0864308 ]]
[[ 0.00979882]
 [ 0.05470903]
 [ 0.05598658]
 [-0.08641351]]
[[ 0.00979657]
 [ 0.05469814]
 [ 0.05597562]
 [-0.08639622]]
[[ 0.00979433]
 [ 0.05468725]
 [ 0.05596466]
 [-0.08637895]]
[[ 0.00979209]
 [ 0.05467637]
 [ 0.05595372]
 [-0.08636168]]
[[ 0.00978985]
 [ 0.05466549]
 [ 0.05594278]
 [-0.08634442]]
[[ 0.00978761]
 [ 0.05465462]
 [ 0.05593184]
 [-0.08632718]]
[[ 0.00978537]
 [ 0.05464375]
 [ 0.05592091]
 [-0.08630994]]
[[ 0.00978313]
 [ 0.05463289]
 [ 0.05590999]
 [-0.08629271]]
[[ 0.0097809 ]
 [ 0.05462204]
 [ 0.05589907]
 [-0.08627549]]
[[ 0.00977866]
 [ 0.0546

[[ 0.00875882]
 [ 0.04960423]
 [ 0.05084992]
 [-0.07832737]]
[[ 0.00875713]
 [ 0.04959581]
 [ 0.05084144]
 [-0.07831405]]
[[ 0.00875543]
 [ 0.04958739]
 [ 0.05083297]
 [-0.07830073]]
[[ 0.00875373]
 [ 0.04957898]
 [ 0.0508245 ]
 [-0.07828742]]
[[ 0.00875204]
 [ 0.04957056]
 [ 0.05081603]
 [-0.07827412]]
[[ 0.00875034]
 [ 0.04956216]
 [ 0.05080757]
 [-0.07826082]]
[[ 0.00874865]
 [ 0.04955375]
 [ 0.05079911]
 [-0.07824753]]
[[ 0.00874696]
 [ 0.04954535]
 [ 0.05079065]
 [-0.07823424]]
[[ 0.00874527]
 [ 0.04953695]
 [ 0.0507822 ]
 [-0.07822096]]
[[ 0.00874358]
 [ 0.04952856]
 [ 0.05077375]
 [-0.07820769]]
[[ 0.00874189]
 [ 0.04952017]
 [ 0.0507653 ]
 [-0.07819442]]
[[ 0.0087402 ]
 [ 0.04951179]
 [ 0.05075686]
 [-0.07818116]]
[[ 0.00873851]
 [ 0.04950341]
 [ 0.05074842]
 [-0.07816791]]
[[ 0.00873682]
 [ 0.04949503]
 [ 0.05073999]
 [-0.07815466]]
[[ 0.00873514]
 [ 0.04948665]
 [ 0.05073156]
 [-0.07814141]]
[[ 0.00873345]
 [ 0.04947828]
 [ 0.05072313]
 [-0.07812817]]
[[ 0.00873177]
 [ 0.0494

[[ 0.00782244]
 [ 0.04491039]
 [ 0.04612304]
 [-0.07091339]]
[[ 0.00782116]
 [ 0.04490392]
 [ 0.04611652]
 [-0.07090319]]
[[ 0.00781989]
 [ 0.04489745]
 [ 0.04611001]
 [-0.07089298]]
[[ 0.00781861]
 [ 0.04489099]
 [ 0.04610349]
 [-0.07088279]]
[[ 0.00781733]
 [ 0.04488453]
 [ 0.04609698]
 [-0.07087259]]
[[ 0.00781606]
 [ 0.04487807]
 [ 0.04609047]
 [-0.0708624 ]]
[[ 0.00781478]
 [ 0.04487161]
 [ 0.04608397]
 [-0.07085221]]
[[ 0.00781351]
 [ 0.04486515]
 [ 0.04607746]
 [-0.07084203]]
[[ 0.00781223]
 [ 0.0448587 ]
 [ 0.04607096]
 [-0.07083185]]
[[ 0.00781096]
 [ 0.04485225]
 [ 0.04606446]
 [-0.07082167]]
[[ 0.00780968]
 [ 0.0448458 ]
 [ 0.04605797]
 [-0.0708115 ]]
[[ 0.00780841]
 [ 0.04483935]
 [ 0.04605147]
 [-0.07080133]]
[[ 0.00780714]
 [ 0.04483291]
 [ 0.04604498]
 [-0.07079117]]
[[ 0.00780587]
 [ 0.04482647]
 [ 0.04603849]
 [-0.07078101]]
[[ 0.0078046 ]
 [ 0.04482003]
 [ 0.04603201]
 [-0.07077086]]
[[ 0.00780333]
 [ 0.0448136 ]
 [ 0.04602552]
 [-0.0707607 ]]
[[ 0.00780206]
 [ 0.0448

[[ 0.00705822]
 [ 0.04100953]
 [ 0.04219162]
 [-0.06476591]]
[[ 0.00705724]
 [ 0.04100446]
 [ 0.0421865 ]
 [-0.06475792]]
[[ 0.00705625]
 [ 0.04099939]
 [ 0.04218139]
 [-0.06474994]]
[[ 0.00705527]
 [ 0.04099432]
 [ 0.04217628]
 [-0.06474195]]
[[ 0.00705428]
 [ 0.04098925]
 [ 0.04217117]
 [-0.06473397]]
[[ 0.0070533 ]
 [ 0.04098418]
 [ 0.04216606]
 [-0.064726  ]]
[[ 0.00705231]
 [ 0.04097911]
 [ 0.04216095]
 [-0.06471802]]
[[ 0.00705133]
 [ 0.04097405]
 [ 0.04215584]
 [-0.06471005]]
[[ 0.00705034]
 [ 0.04096899]
 [ 0.04215074]
 [-0.06470208]]
[[ 0.00704936]
 [ 0.04096393]
 [ 0.04214564]
 [-0.06469411]]
[[ 0.00704838]
 [ 0.04095887]
 [ 0.04214054]
 [-0.06468615]]
[[ 0.0070474 ]
 [ 0.04095381]
 [ 0.04213544]
 [-0.06467819]]
[[ 0.00704641]
 [ 0.04094876]
 [ 0.04213034]
 [-0.06467023]]
[[ 0.00704543]
 [ 0.0409437 ]
 [ 0.04212525]
 [-0.06466227]]
[[ 0.00704445]
 [ 0.04093865]
 [ 0.04212015]
 [-0.06465432]]
[[ 0.00704347]
 [ 0.0409336 ]
 [ 0.04211506]
 [-0.06464636]]
[[ 0.00704249]
 [ 0.0409

[[ 0.0064631 ]
 [ 0.03792735]
 [ 0.03908302]
 [-0.05991671]]
[[ 0.00646231]
 [ 0.03792324]
 [ 0.03907887]
 [-0.05991025]]
[[ 0.00646153]
 [ 0.03791913]
 [ 0.03907472]
 [-0.05990379]]
[[ 0.00646074]
 [ 0.03791502]
 [ 0.03907058]
 [-0.05989733]]
[[ 0.00645995]
 [ 0.03791091]
 [ 0.03906643]
 [-0.05989087]]
[[ 0.00645916]
 [ 0.03790681]
 [ 0.03906229]
 [-0.05988441]]
[[ 0.00645837]
 [ 0.0379027 ]
 [ 0.03905815]
 [-0.05987796]]
[[ 0.00645759]
 [ 0.0378986 ]
 [ 0.03905401]
 [-0.05987151]]
[[ 0.0064568 ]
 [ 0.0378945 ]
 [ 0.03904987]
 [-0.05986506]]
[[ 0.00645601]
 [ 0.03789039]
 [ 0.03904573]
 [-0.05985861]]
[[ 0.00645523]
 [ 0.03788629]
 [ 0.03904159]
 [-0.05985216]]
[[ 0.00645444]
 [ 0.03788219]
 [ 0.03903746]
 [-0.05984572]]
[[ 0.00645365]
 [ 0.0378781 ]
 [ 0.03903332]
 [-0.05983928]]
[[ 0.00645287]
 [ 0.037874  ]
 [ 0.03902919]
 [-0.05983283]]
[[ 0.00645208]
 [ 0.0378699 ]
 [ 0.03902506]
 [-0.0598264 ]]
[[ 0.0064513 ]
 [ 0.03786581]
 [ 0.03902093]
 [-0.05981996]]
[[ 0.00645051]
 [ 0.0378

[[ 0.00604045]
 [ 0.03571431]
 [ 0.03684962]
 [-0.05643894]]
[[ 0.00603978]
 [ 0.03571082]
 [ 0.0368461 ]
 [-0.05643345]]
[[ 0.00603912]
 [ 0.03570733]
 [ 0.03684257]
 [-0.05642797]]
[[ 0.00603846]
 [ 0.03570383]
 [ 0.03683904]
 [-0.05642248]]
[[ 0.00603779]
 [ 0.03570034]
 [ 0.03683552]
 [-0.056417  ]]
[[ 0.00603713]
 [ 0.03569685]
 [ 0.036832  ]
 [-0.05641152]]
[[ 0.00603647]
 [ 0.03569336]
 [ 0.03682848]
 [-0.05640604]]
[[ 0.0060358 ]
 [ 0.03568988]
 [ 0.03682495]
 [-0.05640056]]
[[ 0.00603514]
 [ 0.03568639]
 [ 0.03682143]
 [-0.05639508]]
[[ 0.00603448]
 [ 0.0356829 ]
 [ 0.03681791]
 [-0.0563896 ]]
[[ 0.00603381]
 [ 0.03567942]
 [ 0.0368144 ]
 [-0.05638413]]
[[ 0.00603315]
 [ 0.03567593]
 [ 0.03681088]
 [-0.05637866]]
[[ 0.00603249]
 [ 0.03567245]
 [ 0.03680736]
 [-0.05637318]]
[[ 0.00603183]
 [ 0.03566897]
 [ 0.03680385]
 [-0.05636771]]
[[ 0.00603117]
 [ 0.03566548]
 [ 0.03680033]
 [-0.05636224]]
[[ 0.00603051]
 [ 0.035662  ]
 [ 0.03679682]
 [-0.05635678]]
[[ 0.00602984]
 [ 0.0356

[[ 0.0056467 ]
 [ 0.03363432]
 [ 0.03474932]
 [-0.05317304]]
[[ 0.00564614]
 [ 0.03363135]
 [ 0.03474633]
 [-0.05316838]]
[[ 0.00564558]
 [ 0.03362839]
 [ 0.03474333]
 [-0.05316372]]
[[ 0.00564502]
 [ 0.03362542]
 [ 0.03474033]
 [-0.05315906]]
[[ 0.00564446]
 [ 0.03362245]
 [ 0.03473734]
 [-0.05315441]]
[[ 0.0056439 ]
 [ 0.03361949]
 [ 0.03473434]
 [-0.05314976]]
[[ 0.00564334]
 [ 0.03361652]
 [ 0.03473135]
 [-0.0531451 ]]
[[ 0.00564278]
 [ 0.03361356]
 [ 0.03472835]
 [-0.05314045]]
[[ 0.00564222]
 [ 0.0336106 ]
 [ 0.03472536]
 [-0.0531358 ]]
[[ 0.00564167]
 [ 0.03360763]
 [ 0.03472237]
 [-0.05313115]]
[[ 0.00564111]
 [ 0.03360467]
 [ 0.03471938]
 [-0.0531265 ]]
[[ 0.00564055]
 [ 0.03360171]
 [ 0.03471639]
 [-0.05312185]]
[[ 0.00563999]
 [ 0.03359875]
 [ 0.0347134 ]
 [-0.05311721]]
[[ 0.00563943]
 [ 0.03359579]
 [ 0.03471041]
 [-0.05311256]]
[[ 0.00563888]
 [ 0.03359283]
 [ 0.03470742]
 [-0.05310792]]
[[ 0.00563832]
 [ 0.03358987]
 [ 0.03470443]
 [-0.05310328]]
[[ 0.00563776]
 [ 0.0335

[[ 0.00527157]
 [ 0.03163604]
 [ 0.03273035]
 [-0.05003774]]
[[ 0.0052711 ]
 [ 0.03163353]
 [ 0.03272781]
 [-0.0500338 ]]
[[ 0.00527063]
 [ 0.03163102]
 [ 0.03272528]
 [-0.05002987]]
[[ 0.00527016]
 [ 0.03162851]
 [ 0.03272274]
 [-0.05002593]]
[[ 0.00526969]
 [ 0.031626  ]
 [ 0.0327202 ]
 [-0.05002199]]
[[ 0.00526922]
 [ 0.03162349]
 [ 0.03271767]
 [-0.05001806]]
[[ 0.00526876]
 [ 0.03162098]
 [ 0.03271513]
 [-0.05001412]]
[[ 0.00526829]
 [ 0.03161847]
 [ 0.0327126 ]
 [-0.05001019]]
[[ 0.00526782]
 [ 0.03161596]
 [ 0.03271006]
 [-0.05000625]]
[[ 0.00526735]
 [ 0.03161346]
 [ 0.03270753]
 [-0.05000232]]
[[ 0.00526688]
 [ 0.03161095]
 [ 0.03270499]
 [-0.04999839]]
[[ 0.00526641]
 [ 0.03160844]
 [ 0.03270246]
 [-0.04999446]]
[[ 0.00526594]
 [ 0.03160594]
 [ 0.03269993]
 [-0.04999053]]
[[ 0.00526548]
 [ 0.03160343]
 [ 0.0326974 ]
 [-0.0499866 ]]
[[ 0.00526501]
 [ 0.03160093]
 [ 0.03269487]
 [-0.04998267]]
[[ 0.00526454]
 [ 0.03159843]
 [ 0.03269233]
 [-0.04997874]]
[[ 0.00526407]
 [ 0.0315

In [17]:
print("Final hidden weights: ",end='')
print(*hidden_weights)
print("Final hidden bias: ",end='')
print(*hidden_bias)
print("Final output weights: ",end='')
print(*output_weights)
print("Final output bias: ",end='')
print(*output_bias)

print("\nOutput from neural network after 10,000 epochs: ",end='')
print(*predicted_output)

Final hidden weights: [-3.69399905  0.93524644] [-3.76473753  0.5703548 ]
Final hidden bias: [5.22768157 0.75302081]
Final output weights: [8.56704926] [-2.32129384]
Final output bias: [-1.68742307]

Output from neural network after 10,000 epochs: [0.99480946] [0.96879777] [0.96770812] [0.04935737]
